FROM amazonlinux:2023

ENV GRAALVM_VERSION=23
ENV TARGET_ARCH=aarch64

# Install necessary packages

RUN dnf install -y \
    bash \
    gzip \
    tar

# Install GraalVM

RUN curl -Lo /graalvm.tar.gz "https://download.oracle.com/graalvm/${GRAALVM_VERSION}/latest/graalvm-jdk-${GRAALVM_VERSION}_linux-${TARGET_ARCH}_bin.tar.gz"
RUN mkdir /graalvm
RUN tar -xzvf /graalvm.tar.gz -C /graalvm --strip-components=1
ENV JAVA_HOME=/graalvm
ENV PATH="/graalvm/bin:$PATH"

# Install more packages

RUN dnf install -y \
    gcc \
    glibc-devel \
    git \
    readline-devel \
    autoconf \
    zlib-devel \
    libstdc++-static

RUN dnf clean all

# Install Leiningen

RUN curl -Lo /lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
RUN mv /lein /usr/bin/
RUN chmod +x /usr/bin/lein
RUN lein

# Copy project

COPY . /app
WORKDIR /app

# Run build script

CMD ./build.sh
